language: ruby
rvm:
  - "2.3.0"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsqlite3-dev postgresql-9.3 postgresql-server-dev-9.3 libpq-dev

script:
  - bundle exec rspec
  - bundle exec rubocop
