development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: angadi_online_development
  pool:     5
  username: bala
  password: 
  template: template0

test:
  adapter:  sqlite3
  host:     localhost
  encoding: unicode
  database: angadi_online_test.sqlite3
  pool:     5
  username: bala
  password: 
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: angadi_online_production
  pool:     5
  username: bala
  password: 
  template: template0
